#!/usr/bin/env ruby
require 'bundler/setup'
require 'optparse'
require 'import'

optparser = OptionParser.new
arguments = optparser.parse!

client = arguments.shift
raise ArgumentError, <<~EOS unless client
  Please provide client name as the first argument,
  then the file to import the data from.
EOS

file = arguments.shift
raise ArgumentError, <<~EOS unless file
  Please provide the file to import the data from as the second argument
EOS

Import::Import.call(client, file)
